/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as DuasRouteImport } from './routes/duas'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuranIndexRouteImport } from './routes/quran.index'
import { Route as QuranSurahRouteImport } from './routes/quran.$surah'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedReelsReviewRouteImport } from './routes/_authenticated/reels-review'
import { Route as AuthenticatedMyReelsRouteImport } from './routes/_authenticated/my-reels'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasRoute = DuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/quran/',
  path: '/quran/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranSurahRoute = QuranSurahRouteImport.update({
  id: '/quran/$surah',
  path: '/quran/$surah',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReelsReviewRoute =
  AuthenticatedReelsReviewRouteImport.update({
    id: '/reels-review',
    path: '/reels-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyReelsRoute = AuthenticatedMyReelsRouteImport.update({
  id: '/my-reels',
  path: '/my-reels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/qibla': typeof QiblaRoute
  '/reels': typeof ReelsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my-reels': typeof AuthenticatedMyReelsRoute
  '/reels-review': typeof AuthenticatedReelsReviewRoute
  '/api/chat': typeof ApiChatRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/qibla': typeof QiblaRoute
  '/reels': typeof ReelsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my-reels': typeof AuthenticatedMyReelsRoute
  '/reels-review': typeof AuthenticatedReelsReviewRoute
  '/api/chat': typeof ApiChatRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran': typeof QuranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/qibla': typeof QiblaRoute
  '/reels': typeof ReelsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/my-reels': typeof AuthenticatedMyReelsRoute
  '/_authenticated/reels-review': typeof AuthenticatedReelsReviewRoute
  '/api/chat': typeof ApiChatRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/calendar'
    | '/duas'
    | '/hadith'
    | '/qibla'
    | '/reels'
    | '/admin'
    | '/my-reels'
    | '/reels-review'
    | '/api/chat'
    | '/quran/$surah'
    | '/quran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/calendar'
    | '/duas'
    | '/hadith'
    | '/qibla'
    | '/reels'
    | '/admin'
    | '/my-reels'
    | '/reels-review'
    | '/api/chat'
    | '/quran/$surah'
    | '/quran'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/assistant'
    | '/auth'
    | '/calendar'
    | '/duas'
    | '/hadith'
    | '/qibla'
    | '/reels'
    | '/_authenticated/admin'
    | '/_authenticated/my-reels'
    | '/_authenticated/reels-review'
    | '/api/chat'
    | '/quran/$surah'
    | '/quran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  DuasRoute: typeof DuasRoute
  HadithRoute: typeof HadithRoute
  QiblaRoute: typeof QiblaRoute
  ReelsRoute: typeof ReelsRoute
  ApiChatRoute: typeof ApiChatRoute
  QuranSurahRoute: typeof QuranSurahRoute
  QuranIndexRoute: typeof QuranIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas': {
      id: '/duas'
      path: '/duas'
      fullPath: '/duas'
      preLoaderRoute: typeof DuasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/quran'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/$surah': {
      id: '/quran/$surah'
      path: '/quran/$surah'
      fullPath: '/quran/$surah'
      preLoaderRoute: typeof QuranSurahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reels-review': {
      id: '/_authenticated/reels-review'
      path: '/reels-review'
      fullPath: '/reels-review'
      preLoaderRoute: typeof AuthenticatedReelsReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-reels': {
      id: '/_authenticated/my-reels'
      path: '/my-reels'
      fullPath: '/my-reels'
      preLoaderRoute: typeof AuthenticatedMyReelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMyReelsRoute: typeof AuthenticatedMyReelsRoute
  AuthenticatedReelsReviewRoute: typeof AuthenticatedReelsReviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMyReelsRoute: AuthenticatedMyReelsRoute,
  AuthenticatedReelsReviewRoute: AuthenticatedReelsReviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  DuasRoute: DuasRoute,
  HadithRoute: HadithRoute,
  QiblaRoute: QiblaRoute,
  ReelsRoute: ReelsRoute,
  ApiChatRoute: ApiChatRoute,
  QuranSurahRoute: QuranSurahRoute,
  QuranIndexRoute: QuranIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
